### ISSUE TITLE
Debugging with ZEsarUX does not work on DeZog 0.12.0

### ISSUE THREAD

**Issue by kborowinski** [maziac/DeZog#9] opened 2020-02-21 13:22 UTC
**Describe the bug**
Remote debugging does not work at all with ZEsarUX and DeZog 0.12.0. It works as expected on DeZog 0.11.0. As per instruction in 0.12.0 release I've added **"remoteType": "zrcp"** to *launch.json*

**To Reproduce**
Start ZEsarUX
Launch debugging from VSC
Nothing happens i.e. no error, no output in debug console

![dezog](https://user-images.githubusercontent.com/16168755/75039725-8ed18480-54b9-11ea-90e0-ecb4b3ad101f.gif)

**Version etc. (please complete the following information):**
 - DeZog 0.12.0
 - ZEsarUX SW Version: 8.1 B2

**Additional context**
Please attach your launch.json file.
```json
"version": "0.2.0",
"configurations": [
	{
		"type": "dezog",
		"request": "launch",
		"name": "ZEsarUX",
		"zhostname": "localhost",
		"remoteType": "zrcp",
		"zport": 10000,
		"listFiles": [
			{
				"path": "zxnext.list",
				"useFiles": true,
				"asm": "sjasmplus",
				"mainFile": "zxnext.asm"
			}
		],
		"startAutomatically": false,
		"skipInterrupt": true,
		"commandsAfterLaunch": [
			//"-sprites",
			//"-patterns"
		],
		"disassemblerArgs": {
			"esxdosRst": true
		},
		"rootFolder": "${workspaceFolder}",
		"topOfStack": "stackTop",
		//"load": "../../EMULATORS/ZESARUX/zxnext.sna",
		"load": "../../EMULATORS/ZESARUX/zxnext.nex",
		"smallValuesMaximum": 513,
		"tmpDir": ".tmp",
		"preLaunchTask": "zesarux"
	}
```

**Comment by maziac** [comment] 2020-02-28 11:00
Please try the new version:
https://github.com/maziac/DeZog/releases/tag/0.12.2

(Could you maybe also try the new internal Z80 simulator, "remoteType": "zxsim")

**Comment by kborowinski** [comment] 2020-02-28 12:03
Yep, the remote debugging with ZEsarUX works again on 0.12.2!

I did try the "zxsim" debugging. The simulator starts, runs the z80 code for a bit but then stops executing the code (the debugging is still running and there is no error).  When you pause the debugging then disassembly show some random location im memory (first ROM page address space) with nops:

![zxsim](https://user-images.githubusercontent.com/16168755/75547140-8da8d600-5a2a-11ea-967b-d1e66833aded.gif)

**Comment by maziac** [comment] 2020-02-28 14:14
Fine to hear.

Is this a ZX Next program?
The simulator (currently) does not support Z80N instructions or ZX Next registers.

**Comment by kborowinski** [comment] 2020-02-28 14:17
Nope it's not. I've made sure to run regular Z80 version.

**Comment by maziac** [comment] 2020-02-28 14:42
Can you share the code (or part of it) with me?

**Comment by kborowinski** [comment] 2020-02-28 15:44
Try to debug following code using "zxsim":
```
	ORG $8000
main:
;/*
	di
	ld (restoreStack+1),sp
	ld sp,$7fff
	ei
;*/
	xor a
1	ld hl,$4000
	ld de,$4001
	ld bc,$1800
	ld (hl),a
	ldir
	ld bc,$2ff
	ld (hl),$38
	ldir
	dec a
	jr nz,1B
	di
restoreStack:
	ld sp,0
	ei
	ret
```

**Comment by maziac** [comment] 2020-02-28 17:24
OK, although it is a little slow this works fine for me. 
What is the problem?
![zxsim](https://user-images.githubusercontent.com/3081973/75570436-73d1b800-5a57-11ea-9522-a148d0adbf2f.gif)

**Comment by maziac** [comment] 2020-02-28 17:27
OK. Although it is a little slow this works fine for me.
What is the problem?
![zxsim](https://user-images.githubusercontent.com/3081973/75570664-e2af1100-5a57-11ea-93fd-14c5417be2ec.gif)

**Comment by kborowinski** [comment] 2020-02-29 02:01
That's strange. It does not work on mine computer. There you have full assembly listing. Maybe it has something to do with SNA snapshot? When I change DEVICE type to ZXPSECTRUM48 it does not work at all.

```
;SjASMPlus

	DEVICE ZXSPECTRUM128

	ORG $8000
main:
	di
	ld (restoreStack+1),sp
	ld sp,$7fff
	ei
	xor a
1	ld hl,$4000
	ld de,$4001
	ld bc,$1800
	ld (hl),a
	ldir
	ld bc,$2ff
	ld (hl),$38
	ldir
	dec a
	jr nz,1B
	di
restoreStack:
	ld sp,0
	ei
	ret

	SAVESNA "../../emulators/unreal/qsave1.sna", main
```

**DEVICE ZXSPECTRUM128:**

![dezog_zxsim_1](https://user-images.githubusercontent.com/16168755/75598824-17928680-5a9f-11ea-8028-e2f9c9552815.gif)


**DEVICE ZXSPECTRUM48:**

![dezog_zxsim_2](https://user-images.githubusercontent.com/16168755/75598861-840d8580-5a9f-11ea-9e2a-100888cf8195.gif)

**Comment by maziac** [comment] 2020-02-29 18:27
Thanks to your full listing I could reproduce the problem and fix it here:
https://github.com/maziac/DeZog/releases/tag/0.12.3

The problem was that the IM register was not taken from the SNA file but set to 2 always.
The interrupt kicked in during LDIR and was going nowhere.

**Comment by maziac** [comment] 2020-03-08 07:50
Could you please verify that it is working for you, so I can close this issue.

**Comment by kborowinski** [comment] 2020-03-08 12:13
Yes, it's working now. Thanks!

**Closed** 2020-03-08 15:36 UTC
